"""Commercial-grade input schemas for use case apps (shared by catalog + API)."""

from __future__ import annotations

from typing import Any

LEGACY_PAYMENT_CODE = """
# Legacy payment HSM integration (synthetic)
from Crypto.PublicKey import RSA
from Crypto.Hash import MD5, SHA1
from Crypto.Signature import PKCS1_v1_5

def settle_batch(transactions):
    key = RSA.generate(2048)
    digest = MD5.new(batch_id(transactions).encode())
    return PKCS1_v1_5.new(key).sign(digest)
""".strip()

FRAUD_FEATURE_CODE = (
    "feature_store_key = RSA.import_key(pem)\nscore_hash = MD5.new(features).hexdigest()"
)

USE_CASE_INPUT_SCHEMAS: dict[str, dict[str, Any]] = {
    "fintech_portfolio_rebalance": {
        "input_fields": [
            {"name": "fund_name", "type": "text", "section": "Organization", "label": "Fund / mandate name", "default": "Northstar Global Tech Fund", "help": "Appears on rebalance report and audit trail"},
            {"name": "client_id", "type": "text", "section": "Organization", "label": "Client ID", "default": "CLI-8842-NA"},
            {"name": "portfolio_manager", "type": "text", "section": "Organization", "label": "Portfolio manager", "default": "Alex Chen"},
            {"name": "region", "type": "select", "section": "Organization", "label": "Trading region", "options": ["Americas", "EMEA", "APAC", "Global"], "default": "Americas"},
            {"name": "assets", "type": "tags", "section": "Portfolio", "label": "Holdings (tickers)", "default": ["AAPL", "MSFT", "NVDA", "GOOGL", "AMZN"], "help": "Symbols to rebalance across"},
            {"name": "budget", "type": "number", "section": "Portfolio", "label": "AUM to allocate (USD)", "min": 10000, "default": 2_500_000},
            {"name": "rebalance_horizon", "type": "select", "section": "Portfolio", "label": "Rebalance cadence", "options": ["monthly", "quarterly", "annual", "ad_hoc"], "default": "quarterly"},
            {"name": "risk", "type": "select", "section": "Portfolio", "label": "Risk profile", "options": ["low", "medium", "high"], "default": "medium"},
            {"name": "benchmark_index", "type": "select", "section": "Portfolio", "label": "Benchmark", "options": ["S&P 500", "NASDAQ-100", "MSCI World", "Custom"], "default": "NASDAQ-100"},
            {"name": "max_single_position_pct", "type": "number", "section": "Portfolio", "label": "Max single position (%)", "min": 5, "max": 100, "default": 35},
            {"name": "esg_screen", "type": "boolean", "section": "Portfolio", "label": "Apply ESG exclusion screen", "default": True},
            {"name": "tax_loss_harvest", "type": "boolean", "section": "Portfolio", "label": "Enable tax-loss harvesting", "default": False},
            {"name": "data_classification", "type": "select", "section": "Compliance & compute", "label": "Data classification", "options": ["public_demo", "internal", "restricted"], "default": "public_demo"},
            {"name": "allow_cloud_quantum", "type": "boolean", "section": "Compliance & compute", "label": "Allow cloud quantum backends", "default": False},
            {"name": "max_cost_usd", "type": "number", "section": "Compliance & compute", "label": "Max compute budget (USD)", "min": 0, "default": 0},
            {"name": "notify_compliance", "type": "boolean", "section": "Compliance & compute", "label": "Email compliance on completion", "default": True},
        ],
        "default_input": {
            "fund_name": "Northstar Global Tech Fund",
            "client_id": "CLI-8842-NA",
            "portfolio_manager": "Alex Chen",
            "region": "Americas",
            "assets": ["AAPL", "MSFT", "NVDA", "GOOGL", "AMZN"],
            "budget": 2_500_000,
            "rebalance_horizon": "quarterly",
            "risk": "medium",
            "benchmark_index": "NASDAQ-100",
            "max_single_position_pct": 35,
            "esg_screen": True,
            "tax_loss_harvest": False,
            "data_classification": "public_demo",
            "allow_cloud_quantum": False,
            "max_cost_usd": 0,
            "notify_compliance": True,
        },
    },
    "logistics_delivery_routes": {
        "input_fields": [
            {"name": "fleet_name", "type": "text", "section": "Operation", "label": "Fleet / operation name", "default": "Metro Same-Day North"},
            {"name": "depot_name", "type": "text", "section": "Operation", "label": "Depot / hub name", "default": "Warehouse Hub"},
            {"name": "operation_date", "type": "text", "section": "Operation", "label": "Service date", "default": "2026-07-15", "help": "YYYY-MM-DD"},
            {"name": "shift", "type": "select", "section": "Operation", "label": "Shift window", "options": ["morning", "afternoon", "evening", "24h"], "default": "morning"},
            {"name": "stops", "type": "tags", "section": "Route", "label": "Delivery stops (first = depot)", "default": ["Warehouse Hub", "Downtown Office", "Airport Cargo", "North Mall", "University", "Hospital", "Industrial Park", "Suburb Depot"]},
            {"name": "vehicle_type", "type": "select", "section": "Fleet", "label": "Vehicle type", "options": ["cargo_van", "box_truck", "e_van", "refrigerated"], "default": "cargo_van"},
            {"name": "driver_count", "type": "number", "section": "Fleet", "label": "Available drivers", "min": 1, "max": 50, "default": 3},
            {"name": "max_route_hours", "type": "number", "section": "Fleet", "label": "Max route duration (hours)", "min": 1, "max": 12, "default": 8},
            {"name": "priority", "type": "select", "section": "Optimization", "label": "Optimize for", "options": ["lowest_cost", "fastest_time", "balanced", "lowest_co2"], "default": "balanced"},
            {"name": "traffic_factor", "type": "select", "section": "Optimization", "label": "Traffic conditions", "options": ["light", "normal", "heavy", "peak"], "default": "normal"},
            {"name": "fuel_price_per_liter", "type": "number", "section": "Optimization", "label": "Fuel price (USD/L)", "min": 0.5, "max": 5, "default": 1.45},
            {"name": "time_windows", "type": "boolean", "section": "Optimization", "label": "Respect customer time windows", "default": True},
            {"name": "return_to_start", "type": "boolean", "section": "Optimization", "label": "Return to depot after route", "default": True},
            {"name": "co2_reporting", "type": "boolean", "section": "Reporting", "label": "Include CO₂ estimate in report", "default": True},
        ],
        "default_input": {
            "fleet_name": "Metro Same-Day North",
            "depot_name": "Warehouse Hub",
            "operation_date": "2026-07-15",
            "shift": "morning",
            "stops": ["Warehouse Hub", "Downtown Office", "Airport Cargo", "North Mall", "University", "Hospital", "Industrial Park", "Suburb Depot"],
            "vehicle_type": "cargo_van",
            "driver_count": 3,
            "max_route_hours": 8,
            "priority": "balanced",
            "traffic_factor": "normal",
            "fuel_price_per_liter": 1.45,
            "time_windows": True,
            "return_to_start": True,
            "co2_reporting": True,
        },
    },
    "bank_legacy_crypto_audit": {
        "input_fields": [
            {"name": "institution_name", "type": "text", "section": "Organization", "label": "Financial institution", "default": "First National Trust"},
            {"name": "system_name", "type": "text", "section": "Organization", "label": "System / gateway name", "default": "Payment HSM Gateway"},
            {"name": "environment", "type": "select", "section": "Organization", "label": "Environment", "options": ["production", "staging", "development"], "default": "production"},
            {"name": "business_owner", "type": "text", "section": "Organization", "label": "Business owner email", "default": "payments-security@bank.example"},
            {"name": "compliance_framework", "type": "select", "section": "Compliance", "label": "Compliance framework", "options": ["PCI-DSS 4.0", "SOX", "GDPR", "Basel III", "FFIEC"], "default": "PCI-DSS 4.0"},
            {"name": "migration_deadline", "type": "text", "section": "Compliance", "label": "PQC migration deadline", "default": "2028-01-01"},
            {"name": "data_classification", "type": "select", "section": "Compliance", "label": "Data classification", "options": ["public", "internal", "restricted", "confidential"], "default": "restricted"},
            {"name": "scan_depth", "type": "select", "section": "Scan settings", "label": "Scan depth", "options": ["quick", "standard", "deep"], "default": "standard"},
            {"name": "lines_of_code", "type": "number", "section": "Scan settings", "label": "Estimated LOC in scope", "min": 100, "default": 12500},
            {"name": "include_dependencies", "type": "boolean", "section": "Scan settings", "label": "Scan third-party dependencies", "default": True},
            {"name": "pqc_algorithm_target", "type": "select", "section": "Scan settings", "label": "Target PQC algorithm", "options": ["ML-KEM-768", "ML-DSA-65", "Hybrid RSA+ML-KEM"], "default": "ML-KEM-768"},
            {"name": "code", "type": "code", "section": "Source code", "label": "Source code to audit", "default": LEGACY_PAYMENT_CODE},
            {"name": "notify_security_team", "type": "boolean", "section": "Workflow", "label": "Notify security team on critical findings", "default": True},
            {"name": "generate_executive_summary", "type": "boolean", "section": "Workflow", "label": "Generate executive PDF summary", "default": True},
        ],
        "default_input": {
            "institution_name": "First National Trust",
            "system_name": "Payment HSM Gateway",
            "environment": "production",
            "business_owner": "payments-security@bank.example",
            "compliance_framework": "PCI-DSS 4.0",
            "migration_deadline": "2028-01-01",
            "data_classification": "restricted",
            "scan_depth": "standard",
            "lines_of_code": 12500,
            "include_dependencies": True,
            "pqc_algorithm_target": "ML-KEM-768",
            "code": LEGACY_PAYMENT_CODE,
            "notify_security_team": True,
            "generate_executive_summary": True,
        },
    },
    "telecom_qkd_link_planning": {
        "input_fields": [
            {"name": "carrier_name", "type": "text", "section": "Network", "label": "Carrier / operator", "default": "MetroFiber Communications"},
            {"name": "link_name", "type": "text", "section": "Network", "label": "Link identifier", "default": "QKD-PILOT-DFW-01"},
            {"name": "city_pair", "type": "text", "section": "Network", "label": "City pair (A ↔ B)", "default": "Downtown ↔ Data Center"},
            {"name": "link_distance_km", "type": "number", "section": "Network", "label": "Fiber distance (km)", "min": 1, "max": 200, "default": 40},
            {"name": "fiber_type", "type": "select", "section": "Network", "label": "Fiber type", "options": ["SMF-28", "G.652.D", "Metro dark fiber"], "default": "SMF-28"},
            {"name": "bits", "type": "number", "section": "QKD simulation", "label": "Raw key bits to simulate", "min": 64, "max": 4096, "default": 4096},
            {"name": "sample_check", "type": "number", "section": "QKD simulation", "label": "QBER sample size", "min": 4, "max": 64, "default": 16},
            {"name": "target_key_rate_kbps", "type": "number", "section": "QKD simulation", "label": "Target key rate (kbps)", "min": 1, "max": 1000, "default": 64},
            {"name": "protocol", "type": "select", "section": "QKD simulation", "label": "Protocol", "options": ["BB84", "E91", "CV-QKD"], "default": "BB84"},
            {"name": "sla_uptime_pct", "type": "number", "section": "SLA", "label": "Required uptime (%)", "min": 95, "max": 99.99, "default": 99.9},
            {"name": "redundant_path", "type": "boolean", "section": "SLA", "label": "Require redundant fiber path", "default": True},
            {"name": "integrate_existing_kms", "type": "boolean", "section": "SLA", "label": "Integrate with existing KMS", "default": True},
        ],
        "default_input": {
            "carrier_name": "MetroFiber Communications",
            "link_name": "QKD-PILOT-DFW-01",
            "city_pair": "Downtown ↔ Data Center",
            "link_distance_km": 40,
            "fiber_type": "SMF-28",
            "bits": 4096,
            "sample_check": 16,
            "target_key_rate_kbps": 64,
            "protocol": "BB84",
            "sla_uptime_pct": 99.9,
            "redundant_path": True,
            "integrate_existing_kms": True,
        },
    },
    "cloud_api_entropy": {
        "input_fields": [
            {"name": "account_email", "type": "text", "section": "Account identity", "label": "Account email", "default": "user@enterprise.example", "help": "Primary account identifier encrypted in the vault"},
            {"name": "account_display_name", "type": "text", "section": "Account identity", "label": "Display name", "default": "Alex Chen"},
            {"name": "account_roles", "type": "tags", "section": "Account identity", "label": "Account roles", "default": ["user", "billing_admin"]},
            {"name": "mfa_enabled", "type": "boolean", "section": "Account identity", "label": "MFA enabled", "default": True},
            {"name": "gateway_name", "type": "text", "section": "Service", "label": "Identity gateway", "default": "identity-edge-gw-prod"},
            {"name": "api_environment", "type": "select", "section": "Service", "label": "Environment", "options": ["production", "staging", "development"], "default": "production"},
            {"name": "tenant_id", "type": "text", "section": "Service", "label": "Tenant / org ID", "default": "org_7f3a9c2e"},
            {"name": "purpose", "type": "text", "section": "Service", "label": "Vault binding purpose", "default": "zero_trust_session"},
            {"name": "service_tier", "type": "select", "section": "Service", "label": "Service tier", "options": ["standard", "premium", "critical"], "default": "critical"},
            {"name": "pqc_kem", "type": "select", "section": "NIST PQC algorithms", "label": "Key encapsulation (KEM)", "options": ["ML-KEM-768", "ML-KEM-1024"], "default": "ML-KEM-768", "help": "NIST FIPS 203 — resistant to Shor's algorithm"},
            {"name": "pqc_signature", "type": "select", "section": "NIST PQC algorithms", "label": "Digital signature", "options": ["ML-DSA-65", "ML-DSA-87"], "default": "ML-DSA-65", "help": "NIST FIPS 204 — quantum-safe account binding"},
            {"name": "symmetric_cipher", "type": "select", "section": "NIST PQC algorithms", "label": "Symmetric cipher", "options": ["AES-256-GCM"], "default": "AES-256-GCM"},
            {"name": "bytes", "type": "number", "section": "Session entropy", "label": "QRNG nonce bytes", "min": 8, "max": 256, "default": 32},
            {"name": "rotation_interval_sec", "type": "number", "section": "Session entropy", "label": "Key rotation interval (sec)", "min": 60, "max": 86400, "default": 3600},
            {"name": "bind_to_session", "type": "boolean", "section": "Session entropy", "label": "Bind nonce to session ID", "default": True},
            {"name": "compliance", "type": "select", "section": "Compliance", "label": "Compliance target", "options": ["SOC 2 Type II", "PCI-DSS", "FedRAMP Moderate", "ISO 27001", "CNSA 2.0"], "default": "CNSA 2.0"},
            {"name": "audit_log", "type": "boolean", "section": "Compliance", "label": "Write vault audit log entry", "default": True},
            {"name": "rate_limit_per_min", "type": "number", "section": "Compliance", "label": "Rate limit (encryptions/min)", "min": 10, "max": 100000, "default": 5000},
        ],
        "default_input": {
            "account_email": "user@enterprise.example",
            "account_display_name": "Alex Chen",
            "account_roles": ["user", "billing_admin"],
            "mfa_enabled": True,
            "gateway_name": "identity-edge-gw-prod",
            "api_environment": "production",
            "tenant_id": "org_7f3a9c2e",
            "purpose": "zero_trust_session",
            "service_tier": "critical",
            "pqc_kem": "ML-KEM-768",
            "pqc_signature": "ML-DSA-65",
            "symmetric_cipher": "AES-256-GCM",
            "bytes": 32,
            "rotation_interval_sec": 3600,
            "bind_to_session": True,
            "compliance": "CNSA 2.0",
            "audit_log": True,
            "rate_limit_per_min": 5000,
        },
    },
    "automotive_battery_chemistry": {
        "input_fields": [
            {"name": "program_name", "type": "text", "section": "Program", "label": "R&D program name", "default": "Gen-4 Ultra Range Cell"},
            {"name": "oem_partner", "type": "text", "section": "Program", "label": "OEM partner", "default": "Aurora Motors"},
            {"name": "material", "type": "select", "section": "Chemistry", "label": "Cathode chemistry", "options": ["NMC811", "NMC622", "LFP", "Solid-state"], "default": "NMC811"},
            {"name": "cell_format", "type": "select", "section": "Chemistry", "label": "Cell format", "options": ["4680", "2170", "Pouch", "Prismatic"], "default": "4680"},
            {"name": "target_energy_density", "type": "number", "section": "Chemistry", "label": "Target energy density (Wh/kg)", "min": 100, "max": 500, "default": 320},
            {"name": "temperature_c", "type": "number", "section": "Chemistry", "label": "Operating temperature (°C)", "min": -20, "max": 60, "default": 25},
            {"name": "cycle_life_target", "type": "number", "section": "Chemistry", "label": "Target cycle life", "min": 500, "max": 5000, "default": 1500},
            {"name": "qubits", "type": "number", "section": "Quantum model", "label": "Qubits in model", "min": 2, "max": 4, "default": 2},
            {"name": "shots", "type": "number", "section": "Quantum model", "label": "Measurement shots", "min": 256, "max": 8192, "default": 2048},
            {"name": "vqe_iterations", "type": "number", "section": "Quantum model", "label": "VQE iterations (proxy)", "min": 1, "max": 100, "default": 20},
            {"name": "use_error_mitigation", "type": "boolean", "section": "Quantum model", "label": "Apply error mitigation", "default": True},
        ],
        "default_input": {
            "program_name": "Gen-4 Ultra Range Cell",
            "oem_partner": "Aurora Motors",
            "material": "NMC811",
            "cell_format": "4680",
            "target_energy_density": 320,
            "temperature_c": 25,
            "cycle_life_target": 1500,
            "qubits": 2,
            "shots": 2048,
            "vqe_iterations": 20,
            "use_error_mitigation": True,
        },
    },
    "research_simulator_benchmark": {
        "input_fields": [
            {"name": "lab_name", "type": "text", "section": "Project", "label": "Lab / team name", "default": "Quantum Materials Lab"},
            {"name": "project_id", "type": "text", "section": "Project", "label": "Project ID", "default": "QML-2026-014"},
            {"name": "principal_investigator", "type": "text", "section": "Project", "label": "Principal investigator", "default": "Dr. Sam Rivera"},
            {"name": "qubits", "type": "number", "section": "Workload", "label": "Circuit qubits", "min": 2, "max": 4, "default": 2},
            {"name": "shots", "type": "number", "section": "Workload", "label": "Shots per provider", "min": 128, "max": 4096, "default": 512},
            {"name": "circuit_type", "type": "select", "section": "Workload", "label": "Circuit template", "options": ["bell_state", "ghz", "qft_mini", "custom_ansatz"], "default": "bell_state"},
            {"name": "noise_model", "type": "select", "section": "Workload", "label": "Noise model", "options": ["ideal", "depolarizing_light", "depolarizing_heavy"], "default": "depolarizing_light"},
            {"name": "cost_ceiling_usd", "type": "number", "section": "Budget", "label": "Cost ceiling (USD)", "min": 0, "max": 500, "default": 0},
            {"name": "latency_budget_ms", "type": "number", "section": "Budget", "label": "Latency budget (ms)", "min": 100, "max": 60000, "default": 5000},
            {"name": "require_agreement", "type": "boolean", "section": "Budget", "label": "Require cross-provider agreement", "default": True},
            {"name": "export_csv", "type": "boolean", "section": "Reporting", "label": "Export benchmark CSV", "default": True},
        ],
        "default_input": {
            "lab_name": "Quantum Materials Lab",
            "project_id": "QML-2026-014",
            "principal_investigator": "Dr. Sam Rivera",
            "qubits": 2,
            "shots": 512,
            "circuit_type": "bell_state",
            "noise_model": "depolarizing_light",
            "cost_ceiling_usd": 0,
            "latency_budget_ms": 5000,
            "require_agreement": True,
            "export_csv": True,
        },
    },
    "insurance_fraud_feature_probe": {
        "input_fields": [
            {"name": "insurer_name", "type": "text", "section": "Organization", "label": "Insurer name", "default": "Summit Mutual Insurance"},
            {"name": "line_of_business", "type": "select", "section": "Organization", "label": "Line of business", "options": ["auto", "property", "health", "commercial"], "default": "auto"},
            {"name": "model_name", "type": "text", "section": "Organization", "label": "ML model name", "default": "fraud-score-v3.2"},
            {"name": "model_owner", "type": "text", "section": "Organization", "label": "Model owner", "default": "data-science@summit.example"},
            {"name": "pii_level", "type": "select", "section": "Data governance", "label": "PII sensitivity", "options": ["none", "low", "moderate", "high"], "default": "moderate"},
            {"name": "retention_days", "type": "number", "section": "Data governance", "label": "Feature retention (days)", "min": 30, "max": 2555, "default": 365},
            {"name": "code", "type": "code", "section": "Feature store", "label": "Feature-store / scoring code", "default": FRAUD_FEATURE_CODE},
            {"name": "qubits", "type": "number", "section": "Quantum pipeline", "label": "Circuit qubits", "min": 2, "max": 4, "default": 2},
            {"name": "shots", "type": "number", "section": "Quantum pipeline", "label": "Simulation shots", "min": 256, "max": 4096, "default": 1024},
            {"name": "allow_cloud_quantum", "type": "boolean", "section": "Quantum pipeline", "label": "Allow cloud quantum backends", "default": False},
            {"name": "explain_to_auditor", "type": "boolean", "section": "Quantum pipeline", "label": "Generate auditor explanation", "default": True},
            {"name": "block_on_critical_crypto", "type": "boolean", "section": "Policy", "label": "Block run on critical crypto findings", "default": True},
        ],
        "default_input": {
            "insurer_name": "Summit Mutual Insurance",
            "line_of_business": "auto",
            "model_name": "fraud-score-v3.2",
            "model_owner": "data-science@summit.example",
            "pii_level": "moderate",
            "retention_days": 365,
            "code": FRAUD_FEATURE_CODE,
            "qubits": 2,
            "shots": 1024,
            "allow_cloud_quantum": False,
            "explain_to_auditor": True,
            "block_on_critical_crypto": True,
        },
    },
    "pharma_molecular_binding": {
        "input_fields": [
            {"name": "program_name", "type": "text", "section": "Program", "label": "Drug program name", "default": "Oncology KRAS G12C Phase II"},
            {"name": "compound_name", "type": "text", "section": "Molecule", "label": "Compound name", "default": "KRAS-G12C inhibitor"},
            {"name": "compound_id", "type": "text", "section": "Molecule", "label": "Compound ID", "default": "CMP-2026-0142"},
            {"name": "target_protein", "type": "text", "section": "Molecule", "label": "Target protein", "default": "KRAS G12C"},
            {"name": "binding_site", "type": "select", "section": "Molecule", "label": "Binding site", "options": ["orthosteric", "allosteric", "covalent"], "default": "covalent"},
            {"name": "ph", "type": "number", "section": "Conditions", "label": "Simulated pH", "min": 5, "max": 9, "default": 7.4},
            {"name": "temperature_k", "type": "number", "section": "Conditions", "label": "Temperature (K)", "min": 270, "max": 320, "default": 310},
            {"name": "qubits", "type": "number", "section": "Quantum model", "label": "Active-space qubits", "min": 2, "max": 8, "default": 4},
            {"name": "shots", "type": "number", "section": "Quantum model", "label": "Measurement shots", "min": 512, "max": 16384, "default": 4096},
            {"name": "vqe_iterations", "type": "number", "section": "Quantum model", "label": "VQE iterations", "min": 10, "max": 200, "default": 40},
            {"name": "basis_set", "type": "select", "section": "Quantum model", "label": "Basis set proxy", "options": ["STO-3G", "6-31G", "cc-pVDZ"], "default": "6-31G"},
            {"name": "fda_submission_track", "type": "boolean", "section": "Regulatory", "label": "Include FDA computational evidence format", "default": True},
        ],
        "default_input": {
            "program_name": "Oncology KRAS G12C Phase II",
            "compound_name": "KRAS-G12C inhibitor",
            "compound_id": "CMP-2026-0142",
            "target_protein": "KRAS G12C",
            "binding_site": "covalent",
            "ph": 7.4,
            "temperature_k": 310,
            "qubits": 4,
            "shots": 4096,
            "vqe_iterations": 40,
            "basis_set": "6-31G",
            "fda_submission_track": True,
        },
    },
    "energy_grid_quantum_dispatch": {
        "input_fields": [
            {"name": "grid_operator", "type": "text", "section": "Grid", "label": "ISO / RTO operator", "default": "PJM Interconnection"},
            {"name": "dispatch_date", "type": "text", "section": "Grid", "label": "Dispatch date", "default": "2026-07-15"},
            {"name": "regions", "type": "tags", "section": "Grid", "label": "Dispatch regions", "default": ["Solar Belt", "Wind North", "Hydro East", "Gas Peaker"]},
            {"name": "peak_demand_mw", "type": "number", "section": "Load", "label": "Peak demand (MW)", "min": 500, "max": 50000, "default": 4200},
            {"name": "renewable_mix_pct", "type": "number", "section": "Load", "label": "Renewable mix (%)", "min": 10, "max": 100, "default": 68},
            {"name": "dispatch_risk", "type": "select", "section": "Optimization", "label": "Dispatch risk profile", "options": ["low", "medium", "high"], "default": "medium"},
            {"name": "n1_contingency", "type": "boolean", "section": "Optimization", "label": "Enforce N-1 contingency reserve", "default": True},
            {"name": "carbon_price_usd_ton", "type": "number", "section": "Optimization", "label": "Carbon price (USD/ton)", "min": 0, "max": 200, "default": 45},
            {"name": "curtailment_cap_pct", "type": "number", "section": "Optimization", "label": "Max renewable curtailment (%)", "min": 0, "max": 30, "default": 5},
            {"name": "real_time_rebalance", "type": "boolean", "section": "Optimization", "label": "Enable 5-min re-dispatch", "default": True},
        ],
        "default_input": {
            "grid_operator": "PJM Interconnection",
            "dispatch_date": "2026-07-15",
            "regions": ["Solar Belt", "Wind North", "Hydro East", "Gas Peaker"],
            "peak_demand_mw": 4200,
            "renewable_mix_pct": 68,
            "dispatch_risk": "medium",
            "n1_contingency": True,
            "carbon_price_usd_ton": 45,
            "curtailment_cap_pct": 5,
            "real_time_rebalance": True,
        },
    },
    "finance_quantum_monte_carlo": {
        "input_fields": [
            {"name": "institution", "type": "text", "section": "Book", "label": "Institution", "default": "Global Investment Bank"},
            {"name": "trading_book", "type": "text", "section": "Book", "label": "Trading book", "default": "Global Rates & FX"},
            {"name": "book_id", "type": "text", "section": "Book", "label": "Book ID", "default": "GRF-2026-Q3"},
            {"name": "notional_usd", "type": "number", "section": "Exposure", "label": "Notional (USD)", "min": 1_000_000, "default": 500_000_000},
            {"name": "risk_horizon", "type": "select", "section": "Exposure", "label": "Risk horizon", "options": ["1d", "10d", "1m", "3m"], "default": "10d"},
            {"name": "confidence_level", "type": "select", "section": "Exposure", "label": "VaR confidence", "options": ["95%", "99%", "99.9%"], "default": "99%"},
            {"name": "simulation_paths", "type": "number", "section": "Simulation", "label": "Classical MC paths", "min": 1000, "max": 1000000, "default": 10000},
            {"name": "qae_qubits", "type": "number", "section": "Simulation", "label": "QAE qubits", "min": 4, "max": 20, "default": 8},
            {"name": "regulatory_framework", "type": "select", "section": "Compliance", "label": "Regulatory framework", "options": ["Basel III", "FRTB", "CCAR", "IFRS 9"], "default": "FRTB"},
            {"name": "include_stressed_scenarios", "type": "boolean", "section": "Compliance", "label": "Include stressed scenarios", "default": True},
        ],
        "default_input": {
            "institution": "Global Investment Bank",
            "trading_book": "Global Rates & FX",
            "book_id": "GRF-2026-Q3",
            "notional_usd": 500_000_000,
            "risk_horizon": "10d",
            "confidence_level": "99%",
            "simulation_paths": 10000,
            "qae_qubits": 8,
            "regulatory_framework": "FRTB",
            "include_stressed_scenarios": True,
        },
    },
    "semiconductor_yield_quantum": {
        "input_fields": [
            {"name": "fab_name", "type": "text", "section": "Fab", "label": "Fab / line name", "default": "TSMC N3 Pilot Line"},
            {"name": "process_node", "type": "select", "section": "Fab", "label": "Process node", "options": ["N3", "N5", "N7", "Intel 18A"], "default": "N3"},
            {"name": "wafer_size", "type": "select", "section": "Fab", "label": "Wafer size", "options": ["200mm", "300mm"], "default": "300mm"},
            {"name": "product_sku", "type": "text", "section": "Fab", "label": "Product SKU", "default": "A17-Pro GPU die"},
            {"name": "lots_per_day", "type": "number", "section": "Production", "label": "Lots per day", "min": 1, "max": 500, "default": 42},
            {"name": "target_yield_pct", "type": "number", "section": "Production", "label": "Target yield (%)", "min": 70, "max": 99.9, "default": 92},
            {"name": "qubits", "type": "number", "section": "Quantum model", "label": "Feature-map qubits", "min": 2, "max": 6, "default": 3},
            {"name": "shots", "type": "number", "section": "Quantum model", "label": "Inference shots", "min": 1024, "max": 32768, "default": 8192},
            {"name": "inline_metrology", "type": "boolean", "section": "Detection", "label": "Inline overlay metrology", "default": True},
            {"name": "alert_latency_ms", "type": "number", "section": "Detection", "label": "Alert latency target (ms)", "min": 1, "max": 100, "default": 10},
        ],
        "default_input": {
            "fab_name": "TSMC N3 Pilot Line",
            "process_node": "N3",
            "wafer_size": "300mm",
            "product_sku": "A17-Pro GPU die",
            "lots_per_day": 42,
            "target_yield_pct": 92,
            "qubits": 3,
            "shots": 8192,
            "inline_metrology": True,
            "alert_latency_ms": 10,
        },
    },
    "ai_llm_quantum_retrieval": {
        "input_fields": [
            {"name": "corpus_name", "type": "text", "section": "RAG pipeline", "label": "Corpus / knowledge base name", "default": "Enterprise Knowledge Base"},
            {"name": "corpus_vectors", "type": "number", "section": "RAG pipeline", "label": "Total embedding vectors", "min": 100000, "default": 100_000_000},
            {"name": "embedding_model", "type": "select", "section": "RAG pipeline", "label": "Embedding model", "options": ["text-embedding-3-large", "e5-mistral-7b", "bge-large", "custom"], "default": "text-embedding-3-large"},
            {"name": "embedding_dims", "type": "number", "section": "RAG pipeline", "label": "Embedding dimensions", "min": 128, "max": 4096, "default": 1536},
            {"name": "query_text", "type": "text", "section": "Query", "label": "Sample query", "default": "What is our Q3 revenue forecast by region?"},
            {"name": "top_k", "type": "number", "section": "Query", "label": "Top-K results", "min": 1, "max": 100, "default": 10},
            {"name": "latency_budget_ms", "type": "number", "section": "SLA", "label": "Latency budget (ms)", "min": 10, "max": 5000, "default": 200},
            {"name": "qubits", "type": "number", "section": "Quantum search", "label": "Amplification qubits", "min": 2, "max": 8, "default": 4},
            {"name": "shots", "type": "number", "section": "Quantum search", "label": "Measurement shots", "min": 512, "max": 16384, "default": 4096},
            {"name": "hybrid_rerank", "type": "boolean", "section": "Quantum search", "label": "Hybrid classical rerank after quantum search", "default": True},
        ],
        "default_input": {
            "corpus_name": "Enterprise Knowledge Base",
            "corpus_vectors": 100_000_000,
            "embedding_model": "text-embedding-3-large",
            "embedding_dims": 1536,
            "query_text": "What is our Q3 revenue forecast by region?",
            "top_k": 10,
            "latency_budget_ms": 200,
            "qubits": 4,
            "shots": 4096,
            "hybrid_rerank": True,
        },
    },
    "genomics_protein_folding": {
        "input_fields": [
            {"name": "lab_name", "type": "text", "section": "Program", "label": "Lab / institution", "default": "Stanford Genomics Institute"},
            {"name": "protein_name", "type": "text", "section": "Protein", "label": "Protein name", "default": "BRCA1 variant R1699Q"},
            {"name": "uniprot_id", "type": "text", "section": "Protein", "label": "UniProt ID", "default": "P38398"},
            {"name": "sequence_length", "type": "number", "section": "Protein", "label": "Sequence length (aa)", "min": 50, "max": 5000, "default": 1863},
            {"name": "organism", "type": "text", "section": "Protein", "label": "Organism", "default": "Homo sapiens"},
            {"name": "disease_context", "type": "select", "section": "Clinical", "label": "Disease context", "options": ["hereditary_cancer", "rare_disease", "autoimmune", "neurodegenerative"], "default": "hereditary_cancer"},
            {"name": "has_pdb_template", "type": "boolean", "section": "Clinical", "label": "Known PDB template exists", "default": False},
            {"name": "temperature_k", "type": "number", "section": "Simulation", "label": "Simulation temperature (K)", "min": 270, "max": 320, "default": 310},
            {"name": "qubits", "type": "number", "section": "Quantum model", "label": "Active-space qubits", "min": 2, "max": 8, "default": 4},
            {"name": "shots", "type": "number", "section": "Quantum model", "label": "VQE measurement shots", "min": 1024, "max": 32768, "default": 8192},
            {"name": "vqe_iterations", "type": "number", "section": "Quantum model", "label": "VQE iterations", "min": 10, "max": 200, "default": 60},
        ],
        "default_input": {
            "lab_name": "Stanford Genomics Institute",
            "protein_name": "BRCA1 variant R1699Q",
            "uniprot_id": "P38398",
            "sequence_length": 1863,
            "organism": "Homo sapiens",
            "disease_context": "hereditary_cancer",
            "has_pdb_template": False,
            "temperature_k": 310,
            "qubits": 4,
            "shots": 8192,
            "vqe_iterations": 60,
        },
    },
    "crypto_pqc_wallet_hardening": {
        "input_fields": [
            {"name": "wallet_name", "type": "text", "section": "Wallet", "label": "Wallet name", "default": "Treasury Multisig v2"},
            {"name": "wallet_address", "type": "text", "section": "Wallet", "label": "Wallet address", "default": "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb"},
            {"name": "chain", "type": "select", "section": "Wallet", "label": "Blockchain", "options": ["Ethereum", "Bitcoin", "Solana", "Polygon", "Arbitrum"], "default": "Ethereum"},
            {"name": "asset_symbol", "type": "text", "section": "Wallet", "label": "Primary asset", "default": "ETH"},
            {"name": "holdings_usd", "type": "number", "section": "Wallet", "label": "Holdings value (USD)", "min": 0, "default": 2_400_000},
            {"name": "signature_scheme", "type": "select", "section": "Current crypto", "label": "Current signature scheme", "options": ["ECDSA/secp256k1", "Ed25519", "RSA-2048"], "default": "ECDSA/secp256k1"},
            {"name": "multisig_threshold", "type": "number", "section": "Current crypto", "label": "Multisig threshold (M-of-N)", "min": 1, "max": 10, "default": 3},
            {"name": "pqc_kem", "type": "select", "section": "PQC migration", "label": "Target KEM", "options": ["ML-KEM-768", "ML-KEM-1024"], "default": "ML-KEM-768"},
            {"name": "pqc_signature", "type": "select", "section": "PQC migration", "label": "Target signature", "options": ["ML-DSA-65", "ML-DSA-87"], "default": "ML-DSA-65"},
            {"name": "migration_timeline", "type": "select", "section": "PQC migration", "label": "Migration timeline", "options": ["Q4 2026", "2027", "2028", "2030"], "default": "2027"},
            {"name": "hndl_risk_acknowledged", "type": "boolean", "section": "Threat model", "label": "Harvest-now-decrypt-later risk acknowledged", "default": True},
        ],
        "default_input": {
            "wallet_name": "Treasury Multisig v2",
            "wallet_address": "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb",
            "chain": "Ethereum",
            "asset_symbol": "ETH",
            "holdings_usd": 2_400_000,
            "signature_scheme": "ECDSA/secp256k1",
            "multisig_threshold": 3,
            "pqc_kem": "ML-KEM-768",
            "pqc_signature": "ML-DSA-65",
            "migration_timeline": "2027",
            "hndl_risk_acknowledged": True,
        },
    },
    "smart_city_traffic_flow": {
        "input_fields": [
            {"name": "metro_name", "type": "text", "section": "Metro", "label": "Metro / city name", "default": "Greater Metro Area"},
            {"name": "dot_agency", "type": "text", "section": "Metro", "label": "DOT / agency", "default": "Regional Transportation Authority"},
            {"name": "intersection_count", "type": "number", "section": "Network", "label": "Signalized intersections", "min": 100, "max": 50000, "default": 5000},
            {"name": "peak_vehicles_per_hour", "type": "number", "section": "Network", "label": "Peak vehicles/hour", "min": 10000, "max": 5000000, "default": 850_000},
            {"name": "avg_commute_min", "type": "number", "section": "Network", "label": "Current avg commute (min)", "min": 5, "max": 120, "default": 34},
            {"name": "optimize_for", "type": "select", "section": "Optimization", "label": "Optimize for", "options": ["commute_time", "co2_emissions", "throughput", "balanced"], "default": "commute_time"},
            {"name": "av_fleet_pct", "type": "number", "section": "Optimization", "label": "Autonomous fleet (%)", "min": 0, "max": 100, "default": 12},
            {"name": "real_time_adaptation", "type": "boolean", "section": "Optimization", "label": "Real-time adaptive phasing", "default": True},
            {"name": "carbon_price_usd_ton", "type": "number", "section": "Reporting", "label": "Carbon price (USD/ton)", "min": 0, "max": 200, "default": 50},
            {"name": "include_transit_priority", "type": "boolean", "section": "Reporting", "label": "Prioritize bus/transit corridors", "default": True},
        ],
        "default_input": {
            "metro_name": "Greater Metro Area",
            "dot_agency": "Regional Transportation Authority",
            "intersection_count": 5000,
            "peak_vehicles_per_hour": 850_000,
            "avg_commute_min": 34,
            "optimize_for": "commute_time",
            "av_fleet_pct": 12,
            "real_time_adaptation": True,
            "carbon_price_usd_ton": 50,
            "include_transit_priority": True,
        },
    },
}


def schema_for(use_case_id: str) -> dict[str, Any]:
    return USE_CASE_INPUT_SCHEMAS.get(use_case_id, {"input_fields": [], "default_input": {}})
